HOME
REM
REM MIT License
REM 
REM Copyright (c) [2016] [Mihail Tsvetogorov]
REM 
REM Permission is hereby granted, free of charge, to any person obtaining a copy
REM of this software and associated documentation files (the "Software"), to deal
REM in the Software without restriction, including without limitation the rights
REM to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
REM copies of the Software, and to permit persons to whom the Software is
REM furnished to do so, subject to the following conditions:
REM 
REM The above copyright notice and this permission notice shall be included in all
REM copies or substantial SerialPortions of the Software.
REM 
REM THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
REM IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
REM FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
REM AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
REM LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
REM OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
REM SOFTWARE.
REM
REM Read keyboard
10 K = -157  REM SETS K TO -157 (RANDOM NEGATIVE VALUE) 
20 K = PEEK(49152)-128 REM USING A PEEK FOR READING THE KEY
30 IF K < 0 GOTO 1 REM CHECKING IF A KEY IS PRESSED
40 IF K = 87 THEN REM if you press "W" (87 IS THE ASCII CODE FOR "W")
50 POKE -16295,0 REM TURN ANUNCIATOR 0 ON
60 FOR I = 1 TO 10 : NEXTI REM DELAY
70 POKE -16296,0 REM TURN ANUNCIATOR 0 OFF
80 GOTO 1 REM GOING TO THE START
90 ELSEIF K = 65 THEN REM if you press "A" (65 IS THE ASCII CODE FOR "A")
100 POKE -16293,0 REM TURN ANUNCIATOR 1 ON
110 FOR I = 1 TO 10 : NEXTI REM DELAY
120 POKE -16294,0 REM TURN ANUNCIATOR 1 OFF
130 GOTO 1 REM GOING TO THE START
140 ELSEIF K = 68 THEN REM if you press "D" (68 IS THE ASCII CODE FOR "D")
150 POKE -16291,0 REM TURN ANUNCIATOR 2 ON
160 FOR I = 1 TO 10 : NEXTI REM DELAY
170 POKE -16292,0 REM TURN ANUNCIATOR 2 OFF
180 GOTO 1 REM GOING TO THE START
190 ELSEIF K = 83 THEN REM if you press "S" (83 IS THE ASCII CODE FOR "S")
200 POKE -16289,0 REM TURN ANUNCIATOR 3 ON
210 FOR I = 1 TO 10 : NEXTI REM DELAY
220 POKE -16290,0 REM TURN ANUNCIATOR 3 OFF
230 GOTO 1 REM GOING TO THE START
240 ELSE PRINT "UNKNOWN COMMAND" REM IF SOMETHING ELSE IS ENTERED
RUN 10
